package permissions

type Permission struct {
	Name        string
	Description string
	Risk        string
}

var Registry = []Permission{
	{Name: "platform.admin", Description: "Administer platform-wide configuration.", Risk: "high"},
	{Name: "platform.roles.view", Description: "View roles, permissions and role assignments.", Risk: "normal"},
	{Name: "platform.roles.manage", Description: "Create, change and delete roles and assign or revoke them; equivalent to administrator access.", Risk: "high"},
	{Name: "platform.audit.view", Description: "Query the audit log.", Risk: "elevated"},
	{Name: "organization.view", Description: "View organization users, teams and locations.", Risk: "normal"},
	{Name: "organization.directory.view", Description: "View observed Directory Groups and their memberships.", Risk: "normal"},
	{Name: "organization.directory.sync", Description: "Request an immediate directory synchronization run.", Risk: "elevated"},
	{Name: "organization.teams.manage", Description: "Create, rename and deactivate Teams and manage their members. Team membership determines which tasks a user with tasks.work can see and which notifications they receive, so this permission indirectly controls task access.", Risk: "elevated"},
	{Name: "tasks.view", Description: "View all tasks. Callers with only tasks.work see just the tasks assigned to them or their Teams.", Risk: "normal"},
	{Name: "tasks.work", Description: "See and work (start, block, unblock, complete) tasks assigned to oneself or to one of one's Teams.", Risk: "normal"},
	{Name: "tasks.recurrence.manage", Description: "Create, change, pause and delete Recurring Task Definitions that generate tasks on a schedule.", Risk: "normal"},
	{Name: "tasks.manage", Description: "Create, edit, assign, cancel and reopen any task and work on any task.", Risk: "normal"},
	{Name: "briefing.view", Description: "View published IT Briefing items.", Risk: "normal"},
	{Name: "briefing.manage", Description: "Create, edit, publish and withdraw IT Briefing items and see drafts and withdrawn items.", Risk: "elevated"},
	{Name: "products.view", Description: "View the product catalog: products, manufacturers and product categories.", Risk: "normal"},
	{Name: "products.manage", Description: "Create and change products, manufacturers and product categories.", Risk: "elevated"},
	{Name: "catalog.manage", Description: "Create and change Catalog Items: form definitions, approval steps and fulfillment task templates; activate and deactivate them.", Risk: "elevated"},
	{Name: "requests.view", Description: "View all service requests, their answers, approvals and fulfillment tasks.", Risk: "elevated"},
	{Name: "requests.manage", Description: "Cancel, put on hold, resume and complete any service request.", Risk: "elevated"},
	{Name: "assets.view", Description: "View assets and device context within authorized scope.", Risk: "normal"},
	{Name: "assets.manage", Description: "Create and update assets within authorized scope.", Risk: "elevated"},
	{Name: "endpoints.view", Description: "View provider-observed Devices, their installed software and endpoint data-quality findings.", Risk: "normal"},
	{Name: "endpoints.manage", Description: "Link and unlink Devices to Assets by hand (also needs assets.view), register normalized software products and run the endpoint provider synchronization (devices and management data) and snapshot ingestion (the sync is covered by this permission; no separate sync permission exists).", Risk: "elevated"},
	{Name: "endpoint.management.view", Description: "View normalized endpoint-management artifacts, assignments and filters, and (together with endpoints.view) the provider-reported observations of a Device; the Expected Applicability views (Device, Assignment Path, reverse lookup of an artifact) need no further permission for assignments and counts but show Device data only with endpoints.view, Directory Group and User views need organization.directory.view, and the Device of a User or the User of a Device needs assets.view (without it the User is unknown, never guessed). An assignment's target group id is shown only to callers who also hold organization.directory.view. endpoints.manage includes this read access.", Risk: "normal"},
	{Name: "integrations.intune.manage", Description: "Administer Intune integration configuration, credentials and synchronization controls.", Risk: "high"},
	{Name: "procurement.view", Description: "View suppliers, procurement requests and purchase orders.", Risk: "normal"},
	{Name: "procurement.manage", Description: "Manage suppliers and procurement requests; create, submit for approval, send, cancel and close purchase orders.", Risk: "elevated"},
	{Name: "inventory.view", Description: "View warehouses, stock balances, the inventory ledger and reservations.", Risk: "normal"},
	{Name: "inventory.manage", Description: "Manage warehouses and storage locations; issue, return, transfer, correct and dispose stock; reserve, release and fulfill reservations; post goods receipts.", Risk: "elevated"},
	{Name: "infrastructure.view", Description: "View Buildings, Rooms, Racks, rack placements (rack elevation), Virtual Machines and the infrastructure site tree; with assets.view also where an Asset is placed.", Risk: "normal"},
	{Name: "infrastructure.manage", Description: "Manage Buildings, Rooms and Racks; place, move and remove Assets in Racks; create, change, assign a hypervisor to and decommission Virtual Machines.", Risk: "elevated"},
	{Name: "services.view", Description: "View IT Services (owner, support team, criticality, status), their dependencies and dependents, and the impact view; Virtual Machine and Location names in them also need infrastructure.view, Asset references assets.view.", Risk: "normal"},
	{Name: "services.manage", Description: "Create and change Services, change their status, retire them, and add or remove their dependencies on Services, Virtual Machines, Assets and Locations.", Risk: "elevated"},
	{Name: "knowledge.view", Description: "Read published internal knowledge articles (published employee articles are readable by every signed-in user).", Risk: "normal"},
	{Name: "knowledge.manage", Description: "Write, publish and retire knowledge articles and read drafts and retired articles.", Risk: "elevated"},
	{Name: "majorincidents.manage", Description: "Declare Major Incidents, post public status updates, move them through their lifecycle and link tickets.", Risk: "elevated"},
	{Name: "problems.manage", Description: "Open Problems, record cause, workaround and resolution, mark Known Errors and link tickets. Reading problems needs tickets.view or tickets.manage.", Risk: "elevated"},
	{Name: "runbooks.execute", Description: "Start and cancel runbook executions, which create tracked tasks. Reading runbooks needs knowledge.view or this permission.", Risk: "elevated"},
	{Name: "tickets.view", Description: "View all tickets and their internal comments. Every signed-in user can raise tickets and read their own.", Risk: "normal"},
	{Name: "tickets.manage", Description: "Work tickets: also reads all tickets and internal comments; assign, set priority, comment internally, resolve, close, reopen and cancel any ticket.", Risk: "elevated"},
	{Name: "changes.view", Description: "View all Changes (risk, rollback plan, maintenance window, affected resources, approvals, execution tasks, history) and the Change impact view. Requesters and owners see their own Changes without it; affected Services need services.view, Virtual Machines and Locations infrastructure.view, Assets assets.view to be shown by name.", Risk: "normal"},
	{Name: "changes.manage", Description: "Create and change Changes, edit their affected resources, submit, assess, schedule, review, close and cancel them, approve emergency changes on a justification and add execution tasks. Scheduling and emergency approval affect other people's maintenance planning.", Risk: "elevated"},
	{Name: "changes.execute", Description: "Run Changes: start, complete and fail them and add execution tasks. The owner of a Change may do the same for that Change without this permission.", Risk: "elevated"},
	{Name: "changes.approve", Description: "Approve infrastructure/service changes according to policy.", Risk: "high"},
	{Name: "planning.view", Description: "View all Initiatives (goal, owner, status, target date, milestones, included Changes, Tasks, Procurement Requests and Services, progress, approvals, history) and the maintenance calendar. Owners see their own Initiatives without it; included records appear by name only with the matching view permission of their module.", Risk: "normal"},
	{Name: "planning.manage", Description: "Create and change Initiatives, their milestones and included records, and drive their lifecycle (start planning, propose for approval, activate, hold, resume, complete, cancel). Proposing chooses the approver; the owner, creator, proposer and editors can never approve.", Risk: "elevated"},
	{Name: "security.view", Description: "View security advisories and vulnerability findings. Device names additionally require endpoints.view.", Risk: "normal"},
	{Name: "security.manage", Description: "Create, import, analyze and manage security advisories and vulnerability findings, excluding risk acceptance.", Risk: "elevated"},
	{Name: "security.accept_risk", Description: "Accept vulnerability finding risk with a reason code and review date.", Risk: "elevated"},
	{Name: "software.view", Description: "View Software Products with their Software Approval Status, Software Versions with their approval history, Software Packages and the provider catalog search.", Risk: "normal"},
	{Name: "software.approve", Description: "Approve, reject and revoke Software Version approvals (never for a version the same person registered or requested) and change a Software Product's approval status (approve, deprecate, retire, block, unblock). Includes software.view.", Risk: "elevated"},
	{Name: "software.package", Description: "Register Software Versions, request their approval, package approved versions through the Software Management Provider, publish packages whose reported installer hash equals the approved hash and run the package synchronization. Includes software.view.", Risk: "elevated"},
	{Name: "deployments.view", Description: "View all Deployment plans (version, intent, rings with gates, approvals, history, validation) and Target Sets with their evaluation and explanation. Example Device names additionally need endpoints.view. Owners and creators see their own plans without it.", Risk: "normal"},
	{Name: "deployments.manage", Description: "Create and change Target Sets and Deployment plans (draft rings, gates, Change windows), validate, schedule and cancel plans. Plans that are high impact additionally need deployments.high_impact. Includes deployments.view.", Risk: "elevated"},
	{Name: "deployments.execute", Description: "Start, pause, resume, halt, cancel and promote the rings of scheduled Deployments within their approved plan and gates (F9 G3); starting needs the write capability SOFTWARE_DEPLOY_WRITE. Promoting a high-impact plan additionally needs deployments.high_impact; the person who planned a high-impact plan cannot start it. Includes deployments.view.", Risk: "elevated"},
	{Name: "deployments.high_impact", Description: "Plan high-impact Deployments: uninstall, supersede, rings on Target Sets selecting all Devices or a root group with its nested groups, and plans targeting at least 200 Devices or 25% of the live Devices; submit such plans for their plan Approval (the planner never approves). Beyond deployments.manage.", Risk: "elevated"},
	{Name: "deployments.approve", Description: "Approve or reject high-impact Deployment plans as their named approver (or approver Team member). Required when the plan is submitted and verified again when the decision is applied; owners, creators, editors, the submitter and the authors and last editors of the plan's Target Sets never approve. Approvers read the plan and its Target Sets' definitions and evaluation counts.", Risk: "elevated"},
	// Remote Access (ADR-0026): reserved, planned and not implemented; no route checks these yet.
	{Name: "remote_access.view", Description: "See whether attended remote access is available for a Device: enabled providers, mapped peers (peer ids masked), freshness of the last observation and why a session is blocked. Does not allow starting a session.", Risk: "normal"},
	{Name: "remote_access.start_attended", Description: "Request and launch an attended remote-access session for a Device from an open Ticket whose affected User is the Device's holder (or with a reason code), through an enabled Remote Access Provider; the user consents in the provider client. Policy may require a second approver. Rate limited; see the own sessions.", Risk: "high"},
	{Name: "remote_access.start_unattended", Description: "Planned (reserved, checked by no route; unattended access, terminal and file transfer are not offered in F10): start an unattended remote-access session on a Device named by an unattended-access policy record, with a linked Ticket.", Risk: "high"},
	{Name: "remote_access.terminal", Description: "Planned (reserved, checked by no route; unattended access, terminal and file transfer are not offered in F10): use the provider's terminal channel inside an authorized remote-access session.", Risk: "high"},
	{Name: "remote_access.file_transfer", Description: "Planned (reserved, checked by no route; unattended access, terminal and file transfer are not offered in F10): transfer files inside an authorized remote-access session.", Risk: "high"},
	{Name: "remote_access.view_sessions", Description: "View all Remote Access Session records and their transitions, including other technicians' sessions. Provider launch links are never stored.", Risk: "elevated"},
	{Name: "remote_access.admin", Description: "Map and unmap Devices to provider peer ids, see unmasked peer ids, cancel or close other technicians' sessions and approve sessions that need a second approver. Provider credentials and unattended-access policy records stay planned.", Risk: "high"},
	{Name: "presence.manage_own", Description: "Create, change and cancel one's own Workforce Presence entries (work location, remote, travelling, unavailable) and read them. Entries carry no reason or note.", Risk: "normal"},
	{Name: "presence.view_availability", Description: "See Operational Availability (available, limited, unavailable, unknown) and Team Coverage counts of the Users in one's own Teams. No entry details.", Risk: "elevated"},
	{Name: "presence.view_entries", Description: "See the entry details of other Users in one's Teams that their owners allowed to be seen, and the names behind Team Coverage counts. Every read is audited (viewer, scope, count; never content).", Risk: "elevated"},
	{Name: "presence.manage_entries", Description: "Create, change and cancel Workforce Presence entries of other Users in one's Teams. Every change is audited per entry.", Risk: "elevated"},
	{Name: "presence.manage_teams", Description: "Set the minimum Team Coverage (and the on-site minimum) of Teams.", Risk: "elevated"},
	{Name: "presence.admin", Description: "Administer Workforce Presence: the runtime switch, the recorded data protection impact assessment and works-council dates, retention, and immediate purge of all entries.", Risk: "high"},
	// Turaco AI (ADR-0029, F12): tools additionally require the permission of the module they read.
	{Name: "ai.use", Description: "Use the Turaco assistant. It never grants more than the User already has: every tool call additionally needs the permission of the module it reads and is limited to the records the User named in the conversation.", Risk: "normal"},
	{Name: "ai.settings.view", Description: "View the AI Provider configuration (never secrets), the data classes allowed per provider, caps and retention.", Risk: "elevated"},
	{Name: "ai.settings.manage", Description: "Configure AI Providers, allowed data classes, caps, conversation retention and the runtime switch of the assistant. Decides which business data may leave the installation for an external provider.", Risk: "high"},
	{Name: "ai.usage.view", Description: "View aggregated AI usage and estimated cost (counts only, no prompts).", Risk: "elevated"},
}
