package permissions

type Permission struct {
	Name        string
	Description string
	Risk        string
}

var Registry = []Permission{
	{Name: "platform.admin", Description: "Administer platform-wide configuration.", Risk: "high"},
	{Name: "platform.roles.view", Description: "View roles, permissions and role assignments.", Risk: "normal"},
	{Name: "platform.roles.manage", Description: "Create, change and delete roles and assign or revoke them; equivalent to administrator access.", Risk: "high"},
	{Name: "platform.audit.view", Description: "Query the audit log.", Risk: "elevated"},
	{Name: "organization.view", Description: "View organization users, teams and locations.", Risk: "normal"},
	{Name: "organization.directory.view", Description: "View observed Directory Groups and their memberships.", Risk: "normal"},
	{Name: "organization.directory.sync", Description: "Request an immediate directory synchronization run.", Risk: "elevated"},
	{Name: "organization.teams.manage", Description: "Create, rename and deactivate Teams and manage their members. Team membership determines which tasks a user with tasks.work can see and which notifications they receive, so this permission indirectly controls task access.", Risk: "elevated"},
	{Name: "tasks.view", Description: "View all tasks. Callers with only tasks.work see just the tasks assigned to them or their Teams.", Risk: "normal"},
	{Name: "tasks.work", Description: "See and work (start, block, unblock, complete) tasks assigned to oneself or to one of one's Teams.", Risk: "normal"},
	{Name: "tasks.recurrence.manage", Description: "Create, change, pause and delete Recurring Task Definitions that generate tasks on a schedule.", Risk: "normal"},
	{Name: "tasks.manage", Description: "Create, edit, assign, cancel and reopen any task and work on any task.", Risk: "normal"},
	{Name: "briefing.view", Description: "View published IT Briefing items.", Risk: "normal"},
	{Name: "briefing.manage", Description: "Create, edit, publish and withdraw IT Briefing items and see drafts and withdrawn items.", Risk: "elevated"},
	{Name: "products.view", Description: "View the product catalog: products, manufacturers and product categories.", Risk: "normal"},
	{Name: "products.manage", Description: "Create and change products, manufacturers and product categories.", Risk: "elevated"},
	{Name: "catalog.manage", Description: "Create and change Catalog Items: form definitions, approval steps and fulfillment task templates; activate and deactivate them.", Risk: "elevated"},
	{Name: "requests.view", Description: "View all service requests, their answers, approvals and fulfillment tasks.", Risk: "elevated"},
	{Name: "requests.manage", Description: "Cancel, put on hold, resume and complete any service request.", Risk: "elevated"},
	{Name: "assets.view", Description: "View assets and device context within authorized scope.", Risk: "normal"},
	{Name: "assets.manage", Description: "Create and update assets within authorized scope.", Risk: "elevated"},
	{Name: "endpoints.view", Description: "View provider-observed Devices, their installed software and endpoint data-quality findings.", Risk: "normal"},
	{Name: "endpoints.manage", Description: "Link and unlink Devices to Assets by hand (also needs assets.view), register normalized software products and run the endpoint provider synchronization (devices and management data) and snapshot ingestion (the sync is covered by this permission; no separate sync permission exists).", Risk: "elevated"},
	{Name: "endpoint.management.view", Description: "View normalized endpoint-management artifacts, assignments and filters, and (together with endpoints.view) the provider-reported observations of a Device; the Expected Applicability views (Device, Assignment Path, reverse lookup of an artifact) need no further permission for assignments and counts but show Device data only with endpoints.view, Directory Group and User views need organization.directory.view, and the Device of a User or the User of a Device needs assets.view (without it the User is unknown, never guessed). An assignment's target group id is shown only to callers who also hold organization.directory.view. endpoints.manage includes this read access.", Risk: "normal"},
	{Name: "integrations.intune.manage", Description: "Administer Intune integration configuration, credentials and synchronization controls.", Risk: "high"},
	{Name: "procurement.view", Description: "View suppliers, procurement requests and purchase orders.", Risk: "normal"},
	{Name: "procurement.manage", Description: "Manage suppliers and procurement requests; create, submit for approval, send, cancel and close purchase orders.", Risk: "elevated"},
	{Name: "inventory.view", Description: "View warehouses, stock balances, the inventory ledger and reservations.", Risk: "normal"},
	{Name: "inventory.manage", Description: "Manage warehouses and storage locations; issue, return, transfer, correct and dispose stock; reserve, release and fulfill reservations; post goods receipts.", Risk: "elevated"},
	{Name: "infrastructure.view", Description: "View Buildings, Rooms, Racks, rack placements (rack elevation), Virtual Machines and the infrastructure site tree; with assets.view also where an Asset is placed.", Risk: "normal"},
	{Name: "infrastructure.manage", Description: "Manage Buildings, Rooms and Racks; place, move and remove Assets in Racks; create, change, assign a hypervisor to and decommission Virtual Machines.", Risk: "elevated"},
	{Name: "services.view", Description: "View IT Services (owner, support team, criticality, status), their dependencies and dependents, and the impact view; Virtual Machine and Location names in them also need infrastructure.view, Asset references assets.view.", Risk: "normal"},
	{Name: "services.manage", Description: "Create and change Services, change their status, retire them, and add or remove their dependencies on Services, Virtual Machines, Assets and Locations.", Risk: "elevated"},
	{Name: "knowledge.view", Description: "Read published internal knowledge articles (published employee articles are readable by every signed-in user).", Risk: "normal"},
	{Name: "knowledge.manage", Description: "Write, publish and retire knowledge articles and read drafts and retired articles.", Risk: "elevated"},
	{Name: "majorincidents.manage", Description: "Declare Major Incidents, post public status updates, move them through their lifecycle and link tickets.", Risk: "elevated"},
	{Name: "problems.manage", Description: "Open Problems, record cause, workaround and resolution, mark Known Errors and link tickets. Reading problems needs tickets.view or tickets.manage.", Risk: "elevated"},
	{Name: "runbooks.execute", Description: "Start and cancel runbook executions, which create tracked tasks. Reading runbooks needs knowledge.view or this permission.", Risk: "elevated"},
	{Name: "tickets.view", Description: "View all tickets and their internal comments. Every signed-in user can raise tickets and read their own.", Risk: "normal"},
	{Name: "tickets.manage", Description: "Work tickets: also reads all tickets and internal comments; assign, set priority, comment internally, resolve, close, reopen and cancel any ticket.", Risk: "elevated"},
	{Name: "changes.approve", Description: "Approve infrastructure/service changes according to policy.", Risk: "high"},
	{Name: "deployments.execute", Description: "Start endpoint software/remediation deployments.", Risk: "high"},
	// Remote Access (ADR-0026): reserved, planned and not implemented; no route checks these yet.
	{Name: "remote_access.view", Description: "Planned: see whether remote access is available for a Device or Ticket (provider mapping, supported modes); does not allow starting a session.", Risk: "normal"},
	{Name: "remote_access.start_attended", Description: "Planned: start an attended remote-access session (user consent required) through a Remote Access Provider when policy allows it.", Risk: "high"},
	{Name: "remote_access.start_unattended", Description: "Planned: start an unattended remote-access session on a Device named by an unattended-access policy record, with a linked Ticket.", Risk: "high"},
	{Name: "remote_access.terminal", Description: "Planned: use the provider's terminal channel inside an authorized remote-access session.", Risk: "high"},
	{Name: "remote_access.file_transfer", Description: "Planned: transfer files inside an authorized remote-access session.", Risk: "high"},
	{Name: "remote_access.view_sessions", Description: "Planned: view all Remote Access Session records and their audit trail, including other technicians' sessions.", Risk: "elevated"},
	{Name: "remote_access.admin", Description: "Planned: configure Remote Access Providers, their credentials and unattended-access policy records.", Risk: "high"},
}
