package events

type Definition struct {
	Name        string
	Version     int
	Owner       string
	Description string
	// Internal marks an event only its owner module publishes and consumes
	// (for example the continuation of a chunked fan-out); it is not a
	// contract for other modules.
	Internal bool
}

var Registry = []Definition{
	{Name: "UserSynchronized", Version: 1, Owner: "organization", Description: "Directory sync created or changed a canonical user. Payload: userId, providerKey, created, changedFields (names only), statusChanged; see docs/integrations/ldap-ad-sync-design.md."},
	{Name: "TaskAssigned", Version: 1, Owner: "tasks", Description: "A task was assigned to a User and/or Team. Payload: taskId, assignedUserId, assignedTeamId, previousUserId, previousTeamId."},
	{Name: "TaskCompleted", Version: 1, Owner: "tasks", Description: "A task was completed. Payload: taskId, completedByUserId."},
	{Name: "TaskCancelled", Version: 1, Owner: "tasks", Description: "A task was cancelled, by a person or because the record it belongs to was cancelled. Payload: taskId."},
	{Name: "ApprovalRequested", Version: 1, Owner: "approvals", Description: "An approval step became pending. Payload: approvalId, subjectType, subjectId, stepIndex."},
	{Name: "ApprovalDecided", Version: 1, Owner: "approvals", Description: "An approval was approved or rejected. Payload: approvalId, subjectType, subjectId, stepIndex, decision."},
	{Name: "ServiceRequestApproved", Version: 1, Owner: "requests", Description: "A service request was approved (or needed no approval) and entered fulfillment. Payload: requestId."},
	{Name: "ServiceRequestRejected", Version: 1, Owner: "requests", Description: "A service request was rejected by an approver. Payload: requestId."},
	{Name: "ServiceRequestCompleted", Version: 1, Owner: "requests", Description: "A service request was completed. Payload: requestId."},
	{Name: "ServiceRequestCancelled", Version: 1, Owner: "requests", Description: "A service request was cancelled. Payload: requestId."},
	{Name: "BriefingItemPublished", Version: 1, Owner: "briefing", Description: "A manual IT Briefing item was published. Payload: itemId, severity."},
	{Name: "AssetCreated", Version: 1, Owner: "assets", Description: "A new asset was registered. Payload: assetId, productId."},
	{Name: "AssetAssigned", Version: 1, Owner: "assets", Description: "An asset assignment became active. Payload: assetId, status, operation, assigneeType, assigneeId."},
	{Name: "AssetReturned", Version: 1, Owner: "assets", Description: "An assigned asset was returned. Payload: assetId, status, operation, assigneeType, assigneeId (previous assignee)."},
	{Name: "AssetStatusChanged", Version: 1, Owner: "assets", Description: "An asset changed lifecycle status other than by assignment or return. Payload: assetId, status, operation."},
	{Name: "StockReserved", Version: 1, Owner: "inventory", Description: "Stock or a serialized asset was reserved. Payload: reservationId, kind, productId, status, quantity or assetId, contextType, contextId."},
	{Name: "ReservationReleased", Version: 1, Owner: "inventory", Description: "A reservation was released and its stock or asset is available again. Payload as StockReserved."},
	{Name: "ReservationFulfilled", Version: 1, Owner: "inventory", Description: "A reservation was fulfilled: stock was issued or the reserved asset was assigned. Payload as StockReserved."},
	{Name: "PurchaseOrderApproved", Version: 1, Owner: "procurement", Description: "A purchase order was approved. Payload: orderId, supplierId."},
	{Name: "PurchaseOrderSent", Version: 1, Owner: "procurement", Description: "A purchase order was sent to the supplier. Payload: orderId, supplierId."},
	{Name: "PurchaseOrderReceived", Version: 1, Owner: "procurement", Description: "Every line of a purchase order was received. Payload: orderId, supplierId."},
	{Name: "GoodsReceived", Version: 1, Owner: "inventory", Description: "A goods receipt was posted."},
	{Name: "ServiceRequestSubmitted", Version: 1, Owner: "requests", Description: "A service request was submitted. Payload: requestId."},
	{Name: "KnowledgeArticlePublished", Version: 1, Owner: "knowledge", Description: "A knowledge article was published. Payload: articleId, audience."},
	{Name: "MajorIncidentDeclared", Version: 1, Owner: "service-desk", Description: "A Major Incident was declared. Payload: majorIncidentId, status."},
	{Name: "MajorIncidentUpdated", Version: 1, Owner: "service-desk", Description: "A Major Incident changed status or got a public update. Payload: majorIncidentId, status."},
	{Name: "RunbookExecutionStarted", Version: 1, Owner: "knowledge", Description: "A runbook execution started and created its tasks. Payload: executionId, runbookId."},
	{Name: "RunbookExecutionCompleted", Version: 1, Owner: "knowledge", Description: "Every task of a runbook execution finished. Payload: executionId, runbookId."},
	{Name: "TicketCreated", Version: 1, Owner: "service-desk", Description: "A ticket was created. Payload: ticketId, reporterId, affectedUserId, queueId."},
	{Name: "TicketAssigned", Version: 1, Owner: "service-desk", Description: "A ticket was assigned to a user. Payload: ticketId, assigneeId."},
	{Name: "TicketResolved", Version: 1, Owner: "service-desk", Description: "A ticket was resolved. Payload: ticketId, reporterId, affectedUserId."},
	{Name: "TicketStatusChanged", Version: 1, Owner: "service-desk", Description: "A ticket was reopened, closed or cancelled. Payload: ticketId, operation."},
	{Name: "TicketCommentAdded", Version: 1, Owner: "service-desk", Description: "A comment was added to a ticket. Payload: ticketId, commentId, internal, authorId."},
	{Name: "TicketQueueChanged", Version: 1, Owner: "service-desk", Description: "A ticket was moved to another queue and got a new reference; the old one stays as an alias. Payload: ticketId, fromQueueId, toQueueId, oldReference, newReference."},
	{Name: "RackPlacementChanged", Version: 1, Owner: "infrastructure", Description: "An Asset was placed into, moved within or removed from a Rack. Payload: placementId, rackId, assetId, operation (placed, moved, removed), uPosition, heightU, face; removals also reason."},
	{Name: "VirtualMachineChanged", Version: 1, Owner: "infrastructure", Description: "A Virtual Machine was created, changed, moved to another state or hypervisor, or decommissioned. Payload: virtualMachineId, operation, state, hypervisorAssetId; decommissioning also reason."},
	{Name: "ServiceCreated", Version: 1, Owner: "services", Description: "A Service was created. Payload: serviceId, criticality, status."},
	{Name: "ServiceStatusChanged", Version: 1, Owner: "services", Description: "A Service changed status or was retired. Payload: serviceId, operation (status_changed, retired), status, previousStatus, reason."},
	{Name: "ChangeSubmitted", Version: 1, Owner: "changes", Description: "A draft Change was submitted for assessment. Payload: changeId, kind, risk."},
	{Name: "ChangeApproved", Version: 1, Owner: "changes", Description: "A Change was approved: by its approver, without approval when none was required, or on an emergency justification. Payload: changeId, emergency."},
	{Name: "ChangeRejected", Version: 1, Owner: "changes", Description: "The approver rejected a Change. Payload: changeId."},
	{Name: "ChangeScheduled", Version: 1, Owner: "changes", Description: "An approved Change was scheduled in its maintenance window; published once per scheduling. Payload: changeId, emergency, windowStart, windowEnd."},
	{Name: "ChangeScheduledFanOut", Version: 1, Owner: "changes", Internal: true, Description: "Continuation of the change.scheduled notification fan-out to a large audience (the next chunk of recipients). Payload: changeId, after (the last recipient id already notified)."},
	{Name: "ChangeStarted", Version: 1, Owner: "changes", Description: "A scheduled Change started execution. Payload: changeId."},
	{Name: "ChangeCompleted", Version: 1, Owner: "changes", Description: "A Change in progress was completed. Payload: changeId."},
	{Name: "ChangeFailed", Version: 1, Owner: "changes", Description: "A Change in progress failed. Payload: changeId, reason, rollbackDone."},
	{Name: "PresenceEntryChanged", Version: 1, Owner: "presence", Description: "A Workforce Presence entry was created, rescheduled, relocated, re-recurred or cancelled. Payload: entryId, userId, operation, from, to. Carries no kind, location or reason."},
	{Name: "RemoteAccessSessionRequested", Version: 1, Owner: "remoteaccess", Description: "A Remote Access Session was requested. Payload: sessionId, deviceId, ticketId, provider, approvalRequired."},
	{Name: "RemoteAccessSessionAuthorized", Version: 1, Owner: "remoteaccess", Description: "A Remote Access Session was authorized, at once or by its approver. Payload: sessionId, deviceId, ticketId, provider, status, previousStatus, operation."},
	{Name: "RemoteAccessSessionLaunched", Version: 1, Owner: "remoteaccess", Description: "The technician exchanged the one-time launch handle and the provider client was launched. Payload: sessionId, deviceId, ticketId, provider, status, previousStatus, operation. Never carries the launch link."},
	{Name: "RemoteAccessSessionClosed", Version: 1, Owner: "remoteaccess", Description: "A Remote Access Session ended: closed, rejected, cancelled, expired or failed. Payload: sessionId, deviceId, ticketId, provider, status, previousStatus, operation, reason."},
	{Name: "InitiativeStatusChanged", Version: 1, Owner: "planning", Description: "An Initiative changed status (planning started, proposed, approved, approval rejected, activated, held, resumed, completed, cancelled). Payload: initiativeId, operation, status, previousStatus; hold, cancel and rejection also reason."},
	{Name: "SecurityAdvisoryPublished", Version: 1, Owner: "security", Description: "A Security Advisory became applicable. Payload: advisoryId, severity."},
	{Name: "SecurityAdvisoryPublishedFanOut", Version: 1, Owner: "security", Internal: true, Description: "Continuation of security.advisory notification fan-out. Payload: advisoryId, after, sourceEventId."},
	{Name: "VulnerabilityFindingChanged", Version: 1, Owner: "security", Description: "A vulnerability finding was created or changed status. Payload: findingId, advisoryId, deviceId, status, confidence, operation, previousStatus and reason when applicable."},
	{Name: "DeviceLinked", Version: 1, Owner: "endpoints", Description: "A provider-observed Device was linked to an Asset by serial number match or by hand. Payload: deviceId, assetId, method."},
	{Name: "DeviceUnlinked", Version: 1, Owner: "endpoints", Description: "A Device lost its Asset link: by hand, or because the serial number changed, the serial number is shared by several devices, the device was tombstoned or its manual link collided on revival. Payload: deviceId, assetId, method."},
	{Name: "EndpointFindingRaised", Version: 1, Owner: "endpoints", Description: "An endpoint finding was raised. Payload: findingId, kind and deviceId, softwarePackageId for the package findings package_hash_mismatch and package_published_after_revoke, or deploymentId for deployment_failure_cluster."},
	{Name: "SoftwareVersionApprovalRequested", Version: 1, Owner: "endpoints", Description: "The approval of a Software Version was requested. Payload: versionId, productId."},
	{Name: "SoftwareVersionApprovalRequestedFanOut", Version: 1, Owner: "endpoints", Internal: true, Description: "Continuation of the software.approval_requested notification fan-out. Payload: versionId, after, sourceEventId."},
	{Name: "SoftwareVersionApproved", Version: 1, Owner: "endpoints", Description: "A Software Version was approved, bound to its installer hash. Payload: versionId, productId, installerSha256."},
	{Name: "SoftwareVersionRevoked", Version: 1, Owner: "endpoints", Description: "The approval of a Software Version was revoked. Payload: versionId, productId, reason."},
	{Name: "SoftwarePackagePublished", Version: 1, Owner: "endpoints", Description: "Turaco accepted a Software Package as published into the Management Provider (provider report after a Turaco publish request of an approved version with matching hash; emitted once per package). Payload: packageId, versionId, provider."},
	{Name: "ManagementAssignmentChanged", Version: 1, Owner: "endpoints", Description: "The current assignments of a Management Artifact meaningfully changed during a provider ingestion run: assignments were opened or closed, or a changed assignment was replaced; unchanged re-reads publish nothing. One event per artifact and run. Payload: artifactId, provider, opened, closed."},
	{Name: "ManagementApplicabilityChanged", Version: 1, Owner: "endpoints", Description: "Turaco's expected applicability evaluation meaningfully changed for a managed target."},
	{Name: "TargetSetChanged", Version: 1, Owner: "endpoints", Description: "A Target Set was created, changed or archived. Payload: targetSetId, operation (created|updated|archived), version, allDevices."},
	{Name: "DeploymentScheduled", Version: 1, Owner: "endpoints", Description: "A valid Deployment plan was scheduled (high-impact plans only after their plan Approval, with an unchanged plan). Payload: deploymentId, versionId, productId, intent, highImpact, ringCount."},
	{Name: "DeploymentCancelled", Version: 1, Owner: "endpoints", Description: "A Deployment plan was cancelled with a reason code. Payload: deploymentId, reason, previousStatus."},
	{Name: "DeploymentStarted", Version: 1, Owner: "endpoints", Description: "A scheduled Deployment was started (target resolution begins). Payload: deploymentId, versionId, intent, ringCount, highImpact."},
	{Name: "RingActivated", Version: 1, Owner: "endpoints", Description: "A Deployment Ring became active (first ring after target resolution, next ring after a promotion). Payload: deploymentId, ringId, ringRunId, position."},
	{Name: "RingPromoted", Version: 1, Owner: "endpoints", Description: "A Deployment Ring was promoted (by a person, or the last ring by the engine when the Deployment completes). Payload: deploymentId, ringId, ringRunId, position."},
	{Name: "RingHalted", Version: 1, Owner: "endpoints", Description: "A Deployment Ring was halted (failure threshold, assignment failure, kill switch, a person or cancellation). Payload: deploymentId, ringId, ringRunId, reason."},
	{Name: "DeploymentCompleted", Version: 1, Owner: "endpoints", Description: "A Deployment finished all rings. Payload: deploymentId, status (completed|completed_with_errors), successful, failed."},
	{Name: "DeploymentFailureClusterDetected", Version: 1, Owner: "endpoints", Description: "The correlation found a failure cluster of a Deployment (failed or expired targets sharing an error code, device model, manufacturer, OS version or ring); the Endpoint Finding deployment_failure_cluster was raised. Payload: deploymentId, findingId, dimension, failed."},
	{Name: "DeploymentFailed", Version: 1, Owner: "endpoints", Description: "A Deployment failed before or during execution (target resolution refused, gates closed). Payload: deploymentId, reason."},
	{Name: "AIProviderChanged", Version: 1, Owner: "platform", Description: "An AI Provider was created or reconfigured. Payload: providerId, operation (created, updated), enabled. Carries no endpoint, secret reference or settings."},
	{Name: "ViewShared", Version: 1, Owner: "views", Description: "A Saved View was shared with a User, Team, role or everyone (or the level of a share changed). Payload: viewId, resource, subjectType, subjectId (empty for everyone), level. Carries no name and no filter."},
	{Name: "ViewArchived", Version: 1, Owner: "views", Description: "A Saved View was archived by its owner or an administrator; its shares stop working. Payload: viewId, resource."},
}
